/* =========================================================================
   Spellbook 本地化与图标映射（BlizzCon 2026 demo 技能书）
   SKILL_ZH: 技能英文名 -> 中文名；SKILL_ICONS: 技能英文名 -> Wowhead 图标 slug
   未收录的图标在面板中显示字母缩写占位。
   ========================================================================= */
window.SKILL_ZH = {
  /* ---- 通用 ---- */
  "Attack": "攻击", "Throw": "投掷", "Shoot": "射击", "Shoot Bow": "射箭", "Shoot Crossbow": "射弩",
  "Shoot Gun": "射击(枪)", "Dual Wield": "双武器", "Armor Proficiency": "护甲精通", "Block": "格挡",
  "Dodge": "闪避", "Parry": "招架", "Languages": "语言", "Comprehend Scroll": "通晓卷轴",
  "Beast Training": "野兽训练", "Pick Lock": "开锁", "Assist": "协助", "Attack(宠)": "攻击(宠)",
  "Defensive": "防御(宠)", "Follow": "跟随(宠)", "Passive": "被动(宠)", "Stay": "停留(宠)",
  "Move To": "移动到", "Mine!": "我的！", "Tainted Blood": "污染之血",
  /* ---- 战士 ---- */
  "Battle Stance": "战斗姿态", "Charge": "冲锋", "Hamstring": "断筋", "Heroic Strike": "英勇打击",
  "Mocking Blow": "嘲讽打击", "Overpower": "压制", "Rend": "撕裂", "Retaliation": "反击风暴",
  "Thunder Clap": "雷霆一击", "Victory Rush": "乘胜追击", "Tactical Mastery": "战术掌握",
  "Battle Shout": "战斗怒吼", "Berserker Rage": "狂暴之怒", "Berserker Stance": "狂暴姿态",
  "Challenging Shout": "挑战怒吼", "Cleave": "顺劈斩", "Demoralizing Shout": "挫志怒吼",
  "Execute": "斩杀", "Intimidating Shout": "破胆怒吼", "Pummel": "拳击", "Slam": "猛击",
  "Whirlwind": "旋风斩", "Bloodrage": "血性狂暴", "Defensive Stance": "防御姿态", "Disarm": "缴械",
  "Revenge": "复仇", "Shield Bash": "盾击", "Shield Block": "盾牌格挡", "Shield Wall": "盾墙",
  "Sunder Armor": "破甲攻击", "Taunt": "嘲讽",
  /* ---- 圣骑士 ---- */
  "Blessing of Wisdom": "智慧祝福", "Consecration": "奉献", "Exorcism": "驱邪术", "Flash of Light": "圣光闪现",
  "Holy Light": "圣光术", "Lay on Hands": "圣疗术", "Purify": "纯净术", "Redemption": "救赎",
  "Seal of Light": "光明圣印", "Seal of Righteousness": "正义圣印", "Seal of Wisdom": "智慧圣印",
  "Sense Undead": "感知亡灵", "Turn Undead": "超度亡灵", "Blessing of Freedom": "自由祝福",
  "Blessing of Kings": "王者祝福", "Blessing of Protection": "保护祝福", "Blessing of Salvation": "拯救祝福",
  "Concentration Aura": "专注光环", "Devotion Aura": "虔诚光环", "Divine Intervention": "神圣干涉",
  "Divine Protection": "保护之手", "Divine Shield": "圣盾术", "Fire Resistance Aura": "火焰抗性光环",
  "Frost Resistance Aura": "冰霜抗性光环", "Hammer of Justice": "制裁之锤", "Righteous Fury": "正义之怒",
  "Seal of Fury": "愤怒圣印", "Seal of Justice": "公正圣印", "Shadow Resistance Aura": "暗影抗性光环",
  "Blessing of Might": "力量祝福", "Holy Strike": "神圣打击", "Judgement": "审判", "Retribution Aura": "惩罚光环",
  "Seal of Command": "命令圣印", "Seal of the Crusader": "十字军圣印",
  /* ---- 猎人 ---- */
  "Aspect of the Beast": "野兽守护", "Aspect of the Cheetah": "猎豹守护", "Aspect of the Hawk": "雄鹰守护",
  "Aspect of the Monkey": "灵猴守护", "Beast Lore": "野兽知识", "Call Owl": "召唤猫头鹰",
  "Dismiss Pet": "解散宠物", "Eagle Eye": "鹰眼术", "Eyes of the Beast": "野兽之眼", "Feed Pet": "喂养宠物",
  "Mend Pet": "治疗宠物", "Revive Pet": "复活宠物", "Scare Beast": "恐吓野兽", "Tame Beast": "驯服野兽",
  "Aimed Shot": "瞄准射击", "Arcane Shot": "奥术射击", "Auto Shot": "自动射击", "Concussive Shot": "震荡射击",
  "Distracting Shot": "扰乱射击", "Flare": "照明弹", "Hunter's Mark": "猎人印记", "Multi-Shot": "多重射击",
  "Rapid Fire": "急速射击", "Scorpid Sting": "毒蝎钉刺", "Serpent Sting": "毒蛇钉刺", "Viper Sting": "蝰蛇钉刺",
  "Disengage": "假死逃脱", "Explosive Trap": "爆炸陷阱", "Feign Death": "假死", "Freezing Trap": "冰冻陷阱",
  "Frost Trap": "冰霜陷阱", "Immolation Trap": "献祭陷阱", "Mongoose Bite": "猫鼬撕咬", "Raptor Strike": "猛禽一击",
  "Track Beasts": "追踪野兽", "Track Demons": "追踪恶魔", "Track Elementals": "追踪元素生物",
  "Track Hidden": "追踪隐藏生物", "Track Humanoids": "追踪人形生物", "Track Undead": "追踪亡灵",
  "Wing Clip": "翼龙钉刺", "Claw": "爪击", "Dive": "俯冲", "Great Stamina": "强健体魄", "Growl": "低吼",
  "Natural Armor": "自然护甲",
  /* ---- 盗贼 ---- */
  "Ambush": "伏击", "Cheap Shot": "偷袭", "Eviscerate": "剔骨", "Expose Armor": "破甲",
  "Garrote": "绞喉", "Kidney Shot": "肾击", "Rupture": "割裂", "Slice and Dice": "切割",
  "Adrenaline Rush": "冲动", "Backstab": "背刺", "Blade Flurry": "剑刃乱舞", "Evasion": "闪避",
  "Feint": "佯攻", "Gouge": "凿击", "Kick": "脚踢", "Sinister Strike": "影袭", "Sprint": "疾跑",
  "Blind": "致盲", "Detect Traps": "侦测陷阱", "Disarm Trap": "解除陷阱", "Distract": "扰乱",
  "Pick Pocket": "偷窃", "Sap": "闷棍", "Stealth": "潜行", "Vanish": "消失",
  /* ---- 牧师 ---- */
  "Dispel Magic": "驱散魔法", "Divine Spirit": "神圣之灵", "Elune's Grace": "艾露恩的赐福", "Inner Fire": "心灵之火",
  "Levitate": "漂浮术", "Mana Burn": "法力燃烧", "Power Word: Fortitude": "真言术：韧", "Power Word: Shield": "真言术：盾",
  "Shackle Undead": "束缚亡灵", "Starshards": "星辰碎片", "Abolish Disease": "祛病术", "Cure Disease": "驱除疾病",
  "Fear Ward": "防护恐惧结界", "Flash Heal": "快速治疗", "Heal": "治疗术", "Holy Fire": "神圣之火",
  "Lesser Heal": "次级治疗术", "Prayer of Healing": "治疗祷言", "Renew": "恢复", "Resurrection": "复活术",
  "Smite": "惩击", "Devouring Plague": "噬灵瘟疫", "Fade": "渐隐术", "Mind Blast": "心灵震爆",
  "Mind Control": "精神控制", "Mind Soothe": "安抚心灵", "Mind Vision": "心灵视界", "Psychic Scream": "心灵尖啸",
  "Shadow Protection": "暗影防护", "Shadow Word: Pain": "暗言术：痛",
  /* ---- 萨满 ---- */
  "Call of the Ancestors": "先祖召唤", "Call of the Elements": "元素召唤", "Chain Lightning": "闪电链",
  "Earth Shock": "大地震击", "Earthbind Totem": "地缚图腾", "Fire Nova": "火焰新星", "Flame Shock": "烈焰震击",
  "Frost Shock": "冰霜震击", "Lightning Bolt": "闪电箭", "Magma Totem": "熔岩图腾", "Purge": "净化术",
  "Searing Totem": "灼热图腾", "Stoneclaw Totem": "石爪图腾", "Totemic Recall": "图腾召回", "Astral Recall": "星界传送",
  "Far Sight": "视界术", "Fire Resistance Totem": "火焰抗性图腾", "Flametongue Totem": "火舌图腾",
  "Flametongue Weapon": "火舌武器", "Frost Resistance Totem": "冰霜抗性图腾", "Frostbrand Weapon": "冰封武器",
  "Ghost Wolf": "幽灵狼", "Grounding Totem": "根基图腾", "Lightning Shield": "闪电护盾",
  "Nature Resistance Totem": "自然抗性图腾", "Rockbiter Weapon": "石化武器", "Sentry Totem": "岗哨图腾",
  "Stoneskin Totem": "石肤图腾", "Strength of Earth Totem": "大地之力图腾", "Totemic Projection": "图腾投射",
  "Water Breathing": "水下呼吸", "Water Walking": "水上行走", "Windfury Totem": "风怒图腾",
  "Windfury Weapon": "风怒武器", "Windwall Totem": "风墙图腾", "Ancestral Spirit": "先祖之魂",
  "Cure Poison": "驱除毒素", "Disease Cleansing Totem": "祛病图腾", "Healing Stream Totem": "治疗之泉图腾",
  "Healing Wave": "治疗波", "Lesser Healing Wave": "次级治疗波", "Mana Spring Totem": "法力之泉图腾",
  "Poison Cleansing Totem": "祛毒图腾", "Reincarnation": "复生", "Tremor Totem": "战栗图腾",
  /* ---- 法师 ---- */
  "Amplify Magic": "魔法增效", "Arcane Blast": "奥术冲击", "Arcane Explosion": "奥术爆炸", "Arcane Intellect": "奥术智慧",
  "Arcane Missiles": "奥术飞弹", "Blink": "闪现术", "Conjure Food": "造水术", "Conjure Mana Agate": "制造法力玛瑙",
  "Conjure Mana Jade": "制造法力翡翠", "Conjure Water": "造水术", "Counterspell": "法术反制", "Dampen Magic": "魔法抑制",
  "Evocation": "唤醒", "Mage Armor": "魔甲术", "Mana Shield": "法力护盾", "Polymorph": "变形术",
  "Presence of Mind": "气定神闲", "Remove Lesser Curse": "解除次级诅咒", "Slow Fall": "缓落术",
  "Fire Blast": "火焰冲击", "Fire Ward": "火焰防护结界", "Fireball": "火球术", "Flamestrike": "烈焰风暴",
  "Scorch": "灼烧", "Blizzard": "暴风雪", "Cone of Cold": "冰锥术", "Frost Armor": "霜甲术",
  "Frost Nova": "冰霜新星", "Frost Ward": "冰霜防护结界", "Frostbolt": "寒冰箭", "Ice Armor": "冰甲术",
  /* ---- 术士 ---- */
  "Bane of Agony": "痛苦诅咒", "Corruption": "腐蚀术", "Curse of Recklessness": "鲁莽诅咒",
  "Curse of the Elements": "元素诅咒", "Curse of Tongues": "语言诅咒", "Curse of Weakness": "虚弱诅咒",
  "Drain Life": "吸取生命", "Drain Mana": "吸取法力", "Drain Soul": "吸取灵魂", "Fear": "恐惧术",
  "Life Tap": "生命分流", "Metamorphosis: Demonic Howl": "恶魔变形：恶魔咆哮", "Banish": "放逐术",
  "Create Firestone": "制造火焰石", "Create Healthstone": "制造治疗石", "Create Soulstone": "制造灵魂石",
  "Create Spellstone": "制造法术石", "Demon Armor": "恶魔护甲", "Demon Skin": "恶魔皮肤",
  "Detect Invisibility": "侦测隐形", "Eye of Kilrogg": "基尔罗格之眼", "Health Funnel": "生命通道",
  "Ritual of Summoning": "召唤仪式", "Sense Demons": "感知恶魔", "Shadow Ward": "暗影防护结界",
  "Subjugate Demon": "奴役恶魔", "Summon Felhunter": "召唤地狱猎犬", "Summon Imp": "召唤小鬼",
  "Summon Incubus": "召唤梦魇", "Summon Succubus": "召唤魅魔", "Summon Voidwalker": "召唤虚空行者",
  "Unending Breath": "无尽呼吸", "Hellfire": "地狱烈焰", "Immolate": "献祭", "Rain of Fire": "火焰之雨",
  "Searing Pain": "灼热之痛", "Shadow Bolt": "暗影箭", "Devour Magic": "吞噬魔法", "Spell Lock": "法术封锁",
  /* ---- 德鲁伊 ---- */
  "Entangling Roots": "纠缠根须", "Faerie Fire": "精灵之火", "Hibernate": "休眠", "Moonfire": "月火术",
  "Nature's Grasp": "自然之握", "Omen of Clarity": "清晰预兆", "Soothe Animal": "安抚动物", "Starfire": "星火术",
  "Thorns": "荆棘术", "Wrath": "愤怒", "Aquatic Form": "水栖形态", "Bash": "重击", "Bear Form": "熊形态",
  "Cat Form": "猎豹形态", "Challenging Roar": "挑战咆哮", "Cower": "畏缩", "Dash": "急奔",
  "Demoralizing Roar": "挫志咆哮", "Enrage": "激怒", "Ferocious Bite": "凶猛撕咬", "Frenzied Regeneration": "狂暴回复",
  "Maul": "挥击", "Pounce": "突袭", "Prowl": "潜行", "Rake": "斜掠", "Ravage": "毁灭", "Rip": "撕扯",
  "Shred": "撕碎", "Swipe": "横扫", "Tiger's Fury": "猛虎之怒", "Travel Form": "旅行形态",
  "Abolish Poison": "驱毒术", "Healing Touch": "治疗之触", "Mark of the Wild": "野性印记", "Rebirth": "复生",
  "Regrowth": "回春术", "Rejuvenation": "愈合", "Remove Curse": "解除诅咒", "Revive": "复活", "Tranquility": "宁静"
};
window.SKILL_ICONS = {
  /* 通用 */
  "Dual Wield": "ability_dualwield", "Block": "ability_defend", "Parry": "ability_parry",
  "Dodge":"ability_defend", "Throw": "inv_axe_06",
  /* 战士 */
  "Battle Stance": "ability_warrior_offensivestance", "Charge": "ability_warrior_charge",
  "Hamstring": "ability_shockwave", "Heroic Strike": "ability_rogue_ambush", "Rend": "ability_gouge",
  "Retaliation": "ability_warrior_challange", "Thunder Clap": "spell_nature_thunderclap",
  "Victory Rush": "ability_warrior_devastate", "Battle Shout": "ability_warrior_battleshout",
  "Berserker Rage": "spell_nature_ancestralguardian", "Challenging Shout":"ability_bullrush",
  "Cleave": "ability_warrior_cleave", "Demoralizing Shout": "ability_warrior_warcry",
  "Execute": "inv_sword_48", "Intimidating Shout": "ability_golemthunderclap",
  "Pummel": "inv_gauntlets_04", "Slam": "ability_warrior_decisivestrike", "Whirlwind": "ability_whirlwind",
  "Bloodrage": "ability_racial_bloodrage", "Defensive Stance": "ability_warrior_defensivestance",
  "Disarm": "ability_warrior_disarm", "Revenge": "ability_warrior_revenge",
  "Shield Bash": "ability_warrior_shieldbash", "Shield Block": "ability_defend",
  "Shield Wall": "ability_warrior_shieldwall", "Sunder Armor": "ability_warrior_sunder",
  "Taunt": "spell_nature_reincarnation", "Mocking Blow": "ability_warrior_punishingblow",
  "Overpower":"ability_meleedamage", "Berserker Stance": "ability_racial_avatar",
  "Tactical Mastery": "spell_nature_enchantarmor",
  /* 圣骑士 */
  "Blessing of Wisdom": "spell_holy_sealofwisdom", "Consecration": "spell_holy_innerfire",
  "Exorcism": "spell_holy_excorcism_02", "Flash of Light": "spell_holy_flashheal",
  "Holy Light": "spell_holy_holybolt", "Lay on Hands": "spell_holy_layonhands",
  "Purify": "spell_holy_purify", "Redemption": "spell_holy_resurrection",
  "Seal of Light": "spell_holy_healingaura", "Seal of Righteousness": "ability_thunderbolt",
  "Seal of Wisdom": "spell_holy_righteousnessaura", "Blessing of Freedom": "spell_holy_sealofvalor",
  "Blessing of Kings": "spell_magic_magearmor", "Blessing of Protection": "spell_holy_sealofprotection",
  "Blessing of Salvation": "spell_holy_sealofsalvation", "Concentration Aura": "spell_holy_mindsooth",
  "Devotion Aura": "spell_holy_devotionaura", "Divine Shield": "spell_holy_divineintervention",
  "Hammer of Justice": "spell_holy_sealofmight", "Righteous Fury": "spell_holy_sealoffury",
  "Blessing of Might": "spell_holy_fistofjustice", "Judgement": "spell_holy_righteousfury",
  "Retribution Aura": "spell_holy_auraoflight", "Seal of Command": "ability_warrior_innerrage",
  "Seal of the Crusader": "spell_holy_holysmite", "Holy Strike": "spell_holy_crusaderstrike",
  "Divine Intervention": "spell_nature_timestop", "Divine Protection": "spell_holy_restoration",
  "Fire Resistance Aura": "spell_fire_sealoffire", "Frost Resistance Aura": "spell_frost_wizardmark",
  "Shadow Resistance Aura": "spell_shadow_sealofkings", "Seal of Fury": "spell_holy_sealoffury",
  "Seal of Justice":"spell_holy_sealofwrath", "Turn Undead": "spell_holy_turnundead",
  "Sense Undead": "spell_holy_senseundead",
  /* 猎人 */
  "Aspect of the Beast":"ability_mount_pinktiger", "Aspect of the Cheetah": "ability_mount_jungletiger",
  "Aspect of the Hawk": "spell_nature_ravenform", "Aspect of the Monkey": "ability_hunter_aspectofthemonkey",
  "Beast Lore":"ability_physical_taunt", "Eagle Eye": "ability_hunter_eagleeye",
  "Eyes of the Beast":"ability_eyeoftheowl", "Mend Pet": "ability_hunter_mendpet",
  "Revive Pet":"ability_hunter_beastsoothe", "Scare Beast": "ability_druid_cower",
  "Tame Beast": "ability_hunter_beasttaming", "Aimed Shot": "inv_spear_07", "Arcane Shot": "ability_impalingbolt",
  "Auto Shot": "ability_whirlwind", "Concussive Shot": "spell_frost_stun",
  "Distracting Shot":"spell_arcane_blink", "Flare": "spell_fire_flare",
  "Hunter's Mark": "ability_hunter_snipershot", "Multi-Shot": "ability_upgrademoonglaive",
  "Rapid Fire": "ability_hunter_runningshot", "Serpent Sting": "ability_hunter_quickshot",
  "Viper Sting":"ability_hunter_aimedshot", "Explosive Trap": "spell_fire_selfdestruct",
  "Feign Death": "ability_rogue_feigndeath", "Freezing Trap": "spell_frost_chainsofice",
  "Frost Trap": "spell_frost_freezingbreath", "Immolation Trap": "spell_fire_flameshock",
  "Mongoose Bite": "ability_hunter_swiftstrike", "Raptor Strike":"ability_meleedamage",
  "Wing Clip": "ability_rogue_trip", "Call Owl": "ability_hunter_pet_owl",
  "Dismiss Pet":"spell_nature_spiritwolf", "Feed Pet":"ability_hunter_beasttraining",
  "Scorpid Sting":"ability_hunter_criticalshot", "Disengage":"ability_rogue_feint",
  "Track Beasts": "ability_tracking", "Track Hidden":"ability_stealth",
  "Track Humanoids":"ability_tracking", "Growl": "ability_physical_taunt",
  "Claw": "ability_druid_rake", "Dive": "spell_shadow_burningspirit",
  "Great Stamina": "spell_nature_unyeildingstamina", "Natural Armor": "ability_druid_naturalperfection",
  "Mongoose Bite": "ability_hunter_swiftstrike", "Raptor Strike":"ability_meleedamage",
  "Wing Clip": "ability_rogue_trip",
  /* 盗贼 */
  "Ambush": "ability_rogue_ambush", "Cheap Shot":"ability_cheapshot",
  "Eviscerate": "ability_rogue_eviscerate", "Expose Armor": "ability_warrior_riposte",
  "Garrote": "ability_rogue_garrote", "Kidney Shot": "ability_rogue_kidneyshot",
  "Rupture": "ability_rogue_rupture", "Slice and Dice": "ability_rogue_slicedice",
  "Adrenaline Rush": "spell_shadow_shadowworddominate", "Backstab": "ability_backstab",
  "Blade Flurry": "ability_warrior_punishingblow", "Evasion": "spell_shadow_shadowward",
  "Feint": "ability_rogue_feint", "Gouge": "ability_gouge", "Kick": "ability_kick",
  "Sinister Strike": "spell_shadow_ritualofsacrifice", "Sprint": "ability_rogue_sprint",
  "Blind": "spell_shadow_mindsteal", "Detect Traps":"ability_defend",
  "Disarm Trap":"ability_defend", "Distract": "ability_rogue_distract",
  "Pick Pocket":"ability_stealth", "Sap": "ability_sap", "Stealth": "ability_stealth",
  "Vanish": "ability_vanish",
  /* 牧师 */
  "Dispel Magic": "spell_holy_dispelmagic", "Divine Spirit": "spell_holy_divinespirit",
  "Elune's Grace": "spell_holy_elunesgrace", "Inner Fire": "spell_holy_innerfire",
  "Levitate": "spell_holy_layonhands", "Mana Burn": "spell_shadow_manaburn",
  "Power Word: Fortitude": "spell_holy_wordfortitude", "Power Word: Shield": "spell_holy_powerwordshield",
  "Shackle Undead": "spell_nature_slow", "Starshards": "spell_arcane_starfire",
  "Abolish Disease": "spell_nature_nullifydisease", "Cure Disease": "spell_holy_nullifydisease",
  "Fear Ward":"spell_holy_excorcism", "Flash Heal": "spell_holy_flashheal",
  "Heal": "spell_holy_heal", "Holy Fire": "spell_holy_searinglight",
  "Lesser Heal": "spell_holy_lesserheal", "Prayer of Healing": "spell_holy_prayerofhealing02",
  "Renew": "spell_holy_renew", "Resurrection": "spell_holy_resurrection", "Smite": "spell_holy_holysmite",
  "Devouring Plague": "spell_shadow_devouringplague", "Fade": "spell_magic_lesserinvisibilty",
  "Mind Blast": "spell_shadow_unholyfrenzy", "Mind Control": "spell_shadow_shadowworddominate",
  "Mind Soothe": "spell_holy_mindsooth", "Mind Vision": "spell_holy_mindvision",
  "Psychic Scream": "spell_shadow_psychicscream", "Shadow Protection": "spell_shadow_antishadow",
  "Shadow Word: Pain": "spell_shadow_shadowwordpain",
  /* 萨满 */
  "Call of the Ancestors": "spell_shaman_dropall_02", "Call of the Elements": "spell_shaman_dropall_01",
  "Chain Lightning":"spell_nature_chainlightning", "Earth Shock": "spell_nature_earthshock",
  "Earthbind Totem":"spell_nature_strengthofearthtotem02", "Fire Nova": "spell_fire_sealoffire",
  "Flame Shock": "spell_fire_flameshock", "Frost Shock": "spell_frost_frostshock",
  "Lightning Bolt": "spell_nature_lightning", "Magma Totem": "spell_fire_selfdestruct",
  "Purge": "spell_nature_purge", "Searing Totem": "spell_fire_searingtotem",
  "Stoneclaw Totem": "spell_nature_stoneclawtotem", "Totemic Recall":"spell_nature_stoneclawtotem",
  "Astral Recall": "spell_nature_astralrecal", "Far Sight": "spell_nature_farsight",
  "Fire Resistance Totem":"spell_fireresistancetotem_01", "Flametongue Totem":"spell_nature_guardianward",
  "Flametongue Weapon": "spell_fire_flametounge", "Frost Resistance Totem":"spell_frostresistancetotem_01",
  "Frostbrand Weapon": "spell_frost_frostbrand", "Ghost Wolf":"spell_nature_spiritwolf",
  "Grounding Totem": "spell_nature_groundingtotem", "Lightning Shield": "spell_nature_lightningshield",
  "Nature Resistance Totem": "spell_nature_natureresistancetotem", "Rockbiter Weapon": "spell_nature_rockbiter",
  "Sentry Totem":"spell_nature_stoneclawtotem", "Stoneskin Totem": "spell_nature_stoneskintotem",
  "Strength of Earth Totem": "spell_nature_earthbindtotem", "Totemic Projection":"spell_nature_strengthofearthtotem02",
  "Water Breathing": "spell_shadow_demonbreath", "Water Walking": "spell_frost_windwalkon",
  "Windfury Totem": "spell_nature_windfury", "Windfury Weapon": "spell_nature_cyclone",
  "Windwall Totem": "spell_nature_earthbind", "Ancestral Spirit": "spell_nature_regenerate",
  "Cure Poison": "spell_nature_nullifypoison", "Disease Cleansing Totem": "spell_nature_diseasecleansingtotem",
  "Healing Stream Totem": "inv_spear_04", "Healing Wave": "spell_nature_magicimmunity",
  "Lesser Healing Wave": "spell_nature_healingwavelesser", "Mana Spring Totem": "spell_nature_manaregentotem",
  "Poison Cleansing Totem": "spell_nature_poisoncleansingtotem", "Reincarnation": "spell_nature_reincarnation",
  "Tremor Totem": "spell_nature_tremortotem",
  /* 法师 */
  "Amplify Magic": "spell_holy_flashheal", "Arcane Blast": "spell_arcane_blast",
  "Arcane Explosion": "spell_nature_wispsplode", "Arcane Intellect":"spell_holy_magicalsentry",
  "Arcane Missiles": "spell_nature_starfall", "Blink": "spell_arcane_blink",
  "Conjure Food": "inv_misc_food_10", "Conjure Mana Agate": "inv_misc_gem_emerald_01",
  "Conjure Mana Jade": "inv_misc_gem_emerald_02", "Conjure Water": "inv_drink_06",
  "Counterspell": "spell_frost_iceshock", "Dampen Magic": "spell_nature_abolishmagic",
  "Evocation": "spell_nature_purge", "Mage Armor": "spell_magearmor",
  "Mana Shield": "spell_shadow_detectlesserinvisibility", "Polymorph": "spell_nature_polymorph",
  "Presence of Mind": "spell_nature_enchantarmor", "Remove Lesser Curse": "spell_nature_removecurse",
  "Slow Fall": "spell_magic_featherfall", "Fire Blast": "spell_fire_fireball",
  "Fire Ward": "spell_fire_firearmor", "Fireball": "spell_fire_flamebolt",
  "Flamestrike": "spell_fire_selfdestruct", "Scorch": "spell_fire_soulburn",
  "Blizzard": "spell_frost_icestorm", "Cone of Cold":"spell_frost_glacier",
  "Frost Armor": "spell_frost_frostarmor02", "Frost Nova": "spell_frost_frostnova",
  "Frost Ward": "spell_frost_frostward", "Frostbolt": "spell_frost_frostbolt02",
  "Ice Armor":"spell_frost_frostarmor02",
  /* 术士 */
  "Bane of Agony": "spell_shadow_curseofsargeras", "Corruption": "spell_shadow_abominationexplosion",
  "Curse of Recklessness": "spell_shadow_unholystrength", "Curse of the Elements":"spell_shadow_chilltouch",
  "Curse of Tongues": "spell_shadow_curseoftounges", "Curse of Weakness": "spell_shadow_curseofmannoroth",
  "Drain Life": "spell_shadow_lifedrain02", "Drain Mana": "spell_shadow_siphonmana",
  "Drain Soul": "spell_shadow_haunting", "Fear": "spell_shadow_possession",
  "Life Tap": "spell_shadow_burningspirit", "Metamorphosis: Demonic Howl": "spell_shadow_demonicempathy",
  "Banish": "spell_shadow_cripple", "Create Firestone": "inv_misc_gem_bloodstone_02",
  "Create Healthstone": "inv_stone_04", "Create Soulstone": "inv_misc_orb_04",
  "Create Spellstone": "inv_misc_gem_sapphire_01", "Demon Armor": "spell_shadow_ragingscream",
  "Demon Skin": "spell_shadow_ragingscream", "Detect Invisibility": "spell_shadow_detectinvisibility",
  "Eye of Kilrogg": "spell_shadow_evileye", "Health Funnel": "spell_shadow_lifedrain",
  "Ritual of Summoning": "spell_shadow_twilight", "Sense Demons":"spell_shadow_metamorphosis",
  "Shadow Ward": "spell_shadow_antishadow", "Subjugate Demon": "spell_shadow_enslavedemon",
  "Summon Felhunter": "spell_shadow_summonfelhunter", "Summon Imp": "spell_shadow_summonimp",
  "Summon Incubus": "ability_warlock_incubus", "Summon Succubus": "spell_shadow_summonsuccubus",
  "Summon Voidwalker": "spell_shadow_summonvoidwalker", "Unending Breath": "spell_shadow_demonbreath",
  "Hellfire": "spell_fire_incinerate", "Immolate": "spell_fire_immolation",
  "Rain of Fire": "spell_shadow_rainoffire", "Searing Pain": "spell_fire_soulburn",
  "Shadow Bolt": "spell_shadow_shadowbolt", "Devour Magic":"ability_devour",
  "Spell Lock": "spell_shadow_mindsteal",
  /* 德鲁伊 */
  "Entangling Roots": "spell_nature_stranglevines", "Faerie Fire": "spell_nature_faeriefire",
  "Hibernate": "spell_nature_sleep", "Moonfire": "spell_nature_starfall",
  "Nature's Grasp": "spell_nature_natureswrath", "Omen of Clarity": "spell_nature_crystalball",
  "Soothe Animal":"ability_hunter_beastsoothe", "Starfire": "spell_arcane_starfire",
  "Thorns": "spell_nature_thorns", "Wrath": "spell_nature_abolishmagic",
  "Aquatic Form": "ability_druid_aquaticform", "Bash": "ability_druid_bash",
  "Bear Form":"ability_racial_bearform", "Cat Form": "ability_druid_catform",
  "Challenging Roar": "ability_druid_challangingroar", "Cower": "ability_druid_cower",
  "Dash": "ability_druid_dash", "Demoralizing Roar": "classic_ability_druid_demoralizingroar",
  "Enrage": "ability_druid_enrage", "Ferocious Bite": "ability_druid_ferociousbite",
  "Frenzied Regeneration": "ability_bullrush", "Growl": "ability_physical_taunt",
  "Maul": "ability_druid_maul", "Pounce":"ability_druid_supriseattack",
  "Prowl": "ability_ambush", "Rake": "ability_druid_disembowel",
  "Ravage": "ability_druid_ravage", "Rip": "ability_ghoulfrenzy",
  "Shred": "spell_shadow_vampiricaura", "Swipe": "inv_misc_monsterclaw_03",
  "Tiger's Fury": "ability_mount_jungletiger", "Travel Form": "ability_druid_travelform",
  "Abolish Poison": "spell_nature_nullifypoison_02", "Healing Touch": "spell_nature_healingtouch",
  "Mark of the Wild": "spell_nature_regeneration", "Rebirth":"spell_nature_reincarnation",
  "Regrowth": "spell_nature_resistnature", "Rejuvenation": "spell_nature_rejuvenation",
  "Remove Curse": "spell_holy_removecurse", "Revive":"ability_druid_lunarguidance",
  "Tranquility": "spell_nature_tranquility", "Track Humanoids":"ability_tracking",
  "Claw": "ability_druid_rake", "Mend Pet": "ability_hunter_mendpet"
};
